### ISSUE TITLE
Обновление атрибутов только после перезахода в меню

### ISSUE THREAD

**Issue by HedonisticAI** [varandru/vampire_the_masquerade_character_sheet#12]
В дисциплинах, ритуалах итд добавление отображение новых позиций происходит при смене категории(т.е. атрибуты -> добавить дисциплину или ритуал -> добавленное не появляется на экране -> переход в любую другую категорию -> переход обратно  -> все появляется)

**Comment by HedonisticAI** [comment]
скриншоты 
![Screenshot_20210630_220734_com example vampire_the_masquerade_character_sheet](https://user-images.githubusercontent.com/43443561/124017846-de01c080-d9ef-11eb-868c-d4e5b2292a83.jpg)
![Uploading Screenshot_20210630_220728_com.example.vampire_the_masquerade_character_sheet.jpg…]()

![Screenshot_20210630_220728_com example vampire_the_masquerade_character_sheet](https://user-images.githubusercontent.com/43443561/124017806-d5a98580-d9ef-11eb-95cd-03fbdd5b7e37.jpg)

**Comment by HedonisticAI** [comment]
![Screenshot_20210630_220742_com example vampire_the_masquerade_character_sheet](https://user-images.githubusercontent.com/43443561/124017939-fa056200-d9ef-11eb-8004-f576ac876aa7.jpg)

**Comment by varandru** [comment]
Вроде поправил, перенёс в 1.0.2 для проверки боем
