### ISSUE TITLE
Лимиты при выставлении точек(при любом использовании точек)

### ISSUE THREAD

**Issue by HedonisticAI** [varandru/vampire_the_masquerade_character_sheet#13]

**Comment by HedonisticAI** [comment]
![Uploading Screenshot_20210630_193311_com.example.vampire_the_masquerade_character_sheet.jpg…]()

**Comment by HedonisticAI** [comment]
![Uploading Screenshot_20210630_212839_com.example.vampire_the_masquerade_character_sheet.jpg…]()

**Comment by varandru** [comment]
Поправлены:

- [ ] Атрибуты
- [ ] Способности 
- [ ] Бекграунды

**Comment by varandru** [comment]
Решено в main, см. PR
