### ISSUE TITLE
Описание удаляется при редактировании атрибута/навыка

### ISSUE THREAD

**Issue by HedonisticAI** [varandru/vampire_the_masquerade_character_sheet#14]

**Comment by varandru** [comment]
Дай деталей, пожалуйста. Какие именно разделы? 
[] Добродетели
[] Атрибуты
[] Способности
[] Ещё что-то?

**Comment by varandru** [comment]
Локально больше не воспроизводится. Если воспроизведётся после 1.0.1, предлагаю продолжить в #20
