### ISSUE TITLE
Лимиты числовых значений в логе

### ISSUE THREAD

**Issue by HedonisticAI** [varandru/vampire_the_masquerade_character_sheet#16]

**Comment by HedonisticAI** [comment]
![Screenshot_20210630_215627_com example vampire_the_masquerade_character_sheet](https://user-images.githubusercontent.com/43443561/124022338-57e87880-d9f5-11eb-8d1f-95c842e4f6e4.jpg)
![Screenshot_20210630_215658_com example vampire_the_masquerade_character_sheet](https://user-images.githubusercontent.com/43443561/124022321-53bc5b00-d9f5-11eb-926a-18aa30669b9a.jpg)

**Comment by HedonisticAI** [comment]
(т. е. трата опыта, уровень точки, цена точки, могут быть очень большими( больше int64 в dart) или отрицательными

**Comment by varandru** [comment]
То есть, тот факт, что пробиваются пределы чисел? Или отрицательность?

**Comment by varandru** [comment]
Отрицательность будет исправлена вместе с #13

**Comment by varandru** [comment]
Очень большие числа - в do not fix
