### ISSUE TITLE
darktheme bug

### ISSUE THREAD

**Issue by HedonisticAI** [varandru/vampire_the_masquerade_character_sheet#19]
при включении на honor 9s опции dark theme надписи на боковых панелях(add ritual, add custom merit etc) не видны(актуальный пример в issue 12)

**Comment by varandru** [comment]
Воспроизведено на Xiaomi 5 что-то, не воспроизведено на Google Pixel 4a

**Comment by varandru** [comment]
Вроде, исправлено. Если не будет воспроизводиться в 1.0.1, будет сразу закрыто в 1.0.2
