### ISSUE TITLE
Возможность удалить базовый атрибут

### ISSUE THREAD

**Issue by HedonisticAI** [varandru/vampire_the_masquerade_character_sheet#21]
При редактировании базового attr_name появляется артибуты вида: "Edit attr_name" и он удаляем, что позволяет удалить не только что-то предназнченное к удалению, но и Силу, Ловкость и тому подобное.

**Comment by HedonisticAI** [comment]
К слову, от Edit attr_name при редактировании получается Edit Edit attr_name, к теми же проблемами, что и оригинал, но получить Edit Edit Edit attr_name невозможно, что обидно(

**Comment by varandru** [comment]
Решается в #20, закрою вместе с этой

**Comment by varandru** [comment]
Исправлено в [bdbaacbd427b907c948930337818804ab35d9f75](https://github.com/varandru/vampire_the_masquerade_character_sheet/commit/bdbaacbd427b907c948930337818804ab35d9f75)
