### ISSUE TITLE
Discipline points doesnt work correctly

### ISSUE THREAD

**Issue by HedonisticAI** [varandru/vampire_the_masquerade_character_sheet#41]
![image](https://user-images.githubusercontent.com/43443561/124154699-66d73580-da9e-11eb-82fa-389f004f86e8.png)
 
![image](https://user-images.githubusercontent.com/43443561/124154724-6ccd1680-da9e-11eb-8721-810b1435e073.png)
 
There are supposed 10 be points, but there are 6

**Comment by varandru** [comment]
Fun. Issue to fix: trailing rows do not expand to fill space, stay outside the rendering field instead

**Comment by varandru** [comment]
If nothing else works, just implement #22. I'll have to do it anyway, I just hoped to delay till 1.1
